services:
  postgres:
    image: postgres:16
    container_name: game_arena_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game_arena
    ports:
      - "5432:5432"
    volumes:
      - game_arena_data:/var/lib/postgresql/data

volumes:
  game_arena_data: